package org.meltzg.fs.mtp;

import org.jaudiotagger.audio.AudioFileIO;
import org.jaudiotagger.tag.FieldKey;
import org.junit.*;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.meltzg.fs.mtp.audio.FlacMetadataReader;
import org.meltzg.fs.mtp.audio.RangedByteSource;
import org.meltzg.fs.mtp.types.MTPDeviceIdentifier;

import java.io.IOException;
import java.net.URI;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributeView;
import java.nio.file.attribute.BasicFileAttributes;
import java.nio.file.attribute.FileTime;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import static org.junit.Assert.*;
import static org.junit.Assume.assumeTrue;

/**
 * Integration tests that exercise the MTP filesystem provider against every physically connected
 * device: the parameterized runner enumerates the attached devices and each device's storages, running
 * every test once per (device, storage) so operations are exercised on all storages of all devices.
 * Skipped automatically when no device is present or libmtp is not installed.
 *
 * Run with: ./gradlew integrationTest --tests '*FileSystemIntegration*'
 */
@RunWith(Parameterized.class)
public class MTPFileSystemIntegrationTest {

    private static final String META_FIXTURE = "/fixtures/tagged-track.mp3";

    // Every artifact name carries a token unique to this JVM run and test-method invocation. Some
    // devices apply MTP deletes to their object database asynchronously and, for the rest of the
    // session, refuse to recreate a just-deleted name (SendObject fails with 0x2002 General Error;
    // observed on the FiiO M11 Plus internal storage over WPD). Reusing a fixed name across tests
    // — or across runs on the same connection — therefore poisons it and cascades write failures.
    // Unique names keep every create the first (and only) use of that name in the session; within a
    // single test, replacing writes still reuse one name, which the backend handles in place.
    private static final java.util.concurrent.atomic.AtomicLong ARTIFACT_SEQ =
        new java.util.concurrent.atomic.AtomicLong();
    private final String uniq = Long.toHexString(System.nanoTime()) + "_" + ARTIFACT_SEQ.incrementAndGet();
    private final String TEST_DIR_NAME = "__melt_jfs_test__" + uniq;
    private final String TEST_FILE_NAME = "__melt_jfs_test__" + uniq + ".bin";
    private final String TEST_FILE_NAME2 = "__melt_jfs_test__" + uniq + "moved.bin";
    private final String TEST_DIR_NAME2 = "__melt_jfs_test_moved__" + uniq;
    private final String META_FILE_NAME = "__melt_jfs_test__" + uniq + ".mp3";

    // Fixtures generated by ffmpeg from a CC0 source with these exact tags (see the unit-test
    // fixtures/README.md), uploaded here and read back through the "audio" attribute view.
    private final String AUDIO_FIXTURE_BASE = "__melt_jfs_audio__" + uniq;
    private static final List<String> AUDIO_FIXTURE_EXTENSIONS =
        List.of(".flac", ".mp3", ".m4a", ".ogg", ".opus", ".wav");
    private static final String FIXTURE_TITLE = "melt-jfs Fixture Title";
    private static final String FIXTURE_ARTIST = "melt-jfs Fixture Artist";
    private static final String FIXTURE_ALBUM = "melt-jfs Fixture Album";
    private static final String FIXTURE_GENRE = "Jazz";
    private static final int FIXTURE_TRACK = 7;
    private static final long FIXTURE_DURATION_SECONDS = 4;

    /**
     * One parameter set per (device, storage), labelled with the device's friendly name: every attached
     * device is opened and each of its storages contributes a row, so the storage-level operation tests
     * run once per storage on every device. When the native backend is unavailable, no device is
     * connected, or a device exposes no storages, a single placeholder row is emitted so the class still
     * runs and self-skips in {@link #setUp()} rather than failing the build with an empty parameter list.
     */
    @Parameterized.Parameters(name = "{1} storage={2}")
    public static Collection<Object[]> deviceStorages() throws IOException {
        var params = new ArrayList<Object[]>();
        for (var row : MTPDeviceBridgeIntegrationTest.connectedDevices()) {
            var deviceId = (MTPDeviceIdentifier) row[0];
            var deviceName = (String) row[1];
            if (deviceId == null) {
                params.add(new Object[]{null, deviceName, null});
                continue;
            }
            var provider = new MTPFileSystemProvider();
            try (var fs = provider.newFileSystem(URI.create("mtp://" + deviceId + "/"), null)) {
                var storages = storageNames(fs);
                if (storages.isEmpty()) {
                    params.add(new Object[]{deviceId, deviceName, null});
                } else {
                    for (var storage : storages) {
                        params.add(new Object[]{deviceId, deviceName, storage});
                    }
                }
            } finally {
                MTPDeviceBridge.INSTANCE.close();
            }
        }
        return params;
    }

    /** Logs a reason to stdout whenever a test is skipped, so skips aren't silent in the run output. */
    @Rule
    public final org.junit.rules.TestWatcher skipReasonLogger =
        MTPDeviceBridgeIntegrationTest.skipReasonLogger();

    private final MTPDeviceIdentifier deviceId;
    private final String deviceName;
    private final String storageName;
    private MTPFileSystemProvider provider;
    private MTPFileSystem fs;
    private Path storage;

    public MTPFileSystemIntegrationTest(MTPDeviceIdentifier deviceId, String deviceName, String storageName) {
        this.deviceId = deviceId;
        this.deviceName = deviceName;
        this.storageName = storageName;
    }

    @Before
    public void setUp() throws IOException {
        assumeTrue("native MTP backend not available", isBackendAvailable());
        assumeTrue("no MTP device connected", deviceId != null);
        assumeTrue("device exposes no storages: " + deviceName, storageName != null);
        MTPDeviceBridge.INSTANCE.close();
        var bridge = MTPDeviceBridge.getInstance();
        assumeTrue("device no longer connected: " + deviceName,
            bridge.getDeviceConns().containsKey(deviceId));

        provider = new MTPFileSystemProvider();
        fs = provider.newFileSystem(URI.create("mtp://" + deviceId + "/"), null);

        storage = findStorageByName(storageName);
        assumeTrue("storage no longer present: " + storageName + " on " + deviceName, storage != null);

        // Best-effort cleanup of any leftovers from a previous failed run
        cleanUpTestArtifacts();
    }

    /** Names of the storages a device exposes at its root, used to fan out the parameter sets. */
    private static List<String> storageNames(MTPFileSystem fs) throws IOException {
        var names = new ArrayList<String>();
        try (var stream = Files.newDirectoryStream(fs.getPath("/"))) {
            for (var s : stream) {
                names.add(s.getFileName().toString());
            }
        }
        return names;
    }

    /** Resolves the parameterized storage against the live root listing, or null if it is gone. */
    private Path findStorageByName(String name) throws IOException {
        try (var stream = Files.newDirectoryStream(fs.getPath("/"))) {
            for (var s : stream) {
                if (s.getFileName().toString().equals(name)) return s;
            }
        }
        return null;
    }

    @After
    public void tearDown() throws IOException {
        if (fs != null && fs.isOpen()) {
            cleanUpTestArtifacts();
            fs.close();
        }
        MTPDeviceBridge.INSTANCE.close();
    }

    private void cleanUpTestArtifacts() {
        try {
            if (storage != null) {
                Files.deleteIfExists(storage.resolve(TEST_FILE_NAME));
                Files.deleteIfExists(storage.resolve(TEST_FILE_NAME2));
                Files.deleteIfExists(storage.resolve(META_FILE_NAME));
                for (var ext : AUDIO_FIXTURE_EXTENSIONS) {
                    Files.deleteIfExists(storage.resolve(AUDIO_FIXTURE_BASE + ext));
                }
                deleteTreeQuietly(storage.resolve(TEST_DIR_NAME));
                deleteTreeQuietly(storage.resolve(TEST_DIR_NAME2));
            }
        } catch (IOException ignored) {}
    }

    private void deleteTreeQuietly(Path path) {
        try {
            if (!Files.exists(path)) return;
            if (Files.isDirectory(path)) {
                try (var children = Files.newDirectoryStream(path)) {
                    for (var child : children) deleteTreeQuietly(child);
                }
            }
            Files.deleteIfExists(path);
        } catch (IOException ignored) {}
    }

    // --- root / storage structure ---

    @Test
    public void rootHasDirectoryAttributes() throws IOException {
        var attrs = Files.readAttributes(fs.getPath("/"), BasicFileAttributes.class);
        assertTrue(attrs.isDirectory());
        assertFalse(attrs.isRegularFile());
        assertFalse(attrs.isSymbolicLink());
    }

    @Test
    public void listRootReturnsStorages() throws IOException {
        var storages = listChildren(fs.getPath("/"));
        assertFalse("Expected at least one storage on the device", storages.isEmpty());
        for (var s : storages) {
            assertTrue("Storage root should be a directory: " + s, Files.isDirectory(s));
            assertFalse("Storage root should not be a regular file: " + s, Files.isRegularFile(s));
        }
    }

    @Test
    public void fileStoreReportsConsistentCapacity() throws IOException {
        var storage = requireStorage();
        var store = Files.getFileStore(storage);
        assertTrue("Total space should be > 0", store.getTotalSpace() > 0);
        assertTrue("Usable space should be >= 0", store.getUsableSpace() >= 0);
        assertTrue("Usable space should be <= total space", store.getUsableSpace() <= store.getTotalSpace());
        assertEquals("Unallocated space should equal usable space", store.getUsableSpace(), store.getUnallocatedSpace());
    }

    // --- directory operations ---

    @Test
    public void createDirectoryAppearsInListing() throws IOException {
        var storage = requireStorage();
        var testDir = storage.resolve(TEST_DIR_NAME);

        Files.createDirectory(testDir);
        try {
            var names = listChildren(storage).stream()
                .map(p -> p.getFileName().toString())
                .collect(Collectors.toList());
            assertTrue("Created directory should appear in listing", names.contains(TEST_DIR_NAME));
            assertTrue("Created directory should report isDirectory=true", Files.isDirectory(testDir));
            assertFalse("Created directory should not report isRegularFile=true", Files.isRegularFile(testDir));
        } finally {
            Files.deleteIfExists(testDir);
        }
    }

    @Test
    public void deleteDirectoryDisappearsFromListing() throws IOException {
        var storage = requireStorage();
        var testDir = storage.resolve(TEST_DIR_NAME);

        Files.createDirectory(testDir);
        Files.delete(testDir);

        assertFalse("Deleted directory should not exist", Files.exists(testDir));
        var names = listChildren(storage).stream()
            .map(p -> p.getFileName().toString())
            .collect(Collectors.toList());
        assertFalse("Deleted directory should not appear in listing", names.contains(TEST_DIR_NAME));
    }

    @Test(expected = NoSuchFileException.class)
    public void deleteNonExistentThrows() throws IOException {
        var storage = requireStorage();
        Files.delete(storage.resolve(TEST_DIR_NAME));
    }

    // --- walk ---

    @Test
    public void walkRootDepth1IncludesAllStorages() throws IOException {
        var storages = listChildren(fs.getPath("/"));
        var walked = Files.walk(fs.getPath("/"), 1).collect(Collectors.toList());
        for (var storage : storages) {
            assertTrue("Walk from root should include storage: " + storage, walked.contains(storage));
        }
    }

    @Test
    public void walkStorageIncludesRootEntry() throws IOException {
        var storage = requireStorage();
        var walked = Files.walk(storage, 1).collect(Collectors.toList());
        assertFalse("Walk should produce at least the storage root itself", walked.isEmpty());
        assertTrue("Walk should include the storage root", walked.contains(storage));
    }

    // --- file attributes and content ---

    @Test
    public void fileAttributesAreConsistent() throws IOException {
        var storage = requireStorage();
        var file = requireRegularFile(storage);

        var attrs = Files.readAttributes(file, BasicFileAttributes.class);
        assertTrue("File should report isRegularFile=true", attrs.isRegularFile());
        assertFalse("File should report isDirectory=false", attrs.isDirectory());
        assertTrue("File size should be >= 0", attrs.size() >= 0);
        assertNotNull("File key should not be null", attrs.fileKey());
    }

    @Test
    public void readFileBytesMatchReportedSize() throws IOException {
        var storage = requireStorage();
        var file = requireRegularFile(storage);

        long reportedSize = Files.size(file);
        byte[] content = Files.readAllBytes(file);
        assertNotNull("File content should not be null", content);
        assertEquals("Read byte count should match reported file size", reportedSize, content.length);
    }

    // --- write path ---

    @Test
    public void writeThenReadRoundTrips() throws IOException {
        var storage = requireStorage();
        var file = storage.resolve(TEST_FILE_NAME);
        var payload = "melt-jfs write path éñ 🎵".getBytes(java.nio.charset.StandardCharsets.UTF_8);

        Files.write(file, payload);
        try {
            assertTrue("Written file should exist", Files.exists(file));
            assertTrue("Written file should be a regular file", Files.isRegularFile(file));
            assertFalse("Written file should not be a directory", Files.isDirectory(file));
            assertEquals("Reported size should match payload", payload.length, Files.size(file));
            assertArrayEquals("Round-tripped bytes should match", payload, Files.readAllBytes(file));

            var names = listChildren(storage).stream()
                .map(p -> p.getFileName().toString())
                .collect(Collectors.toList());
            assertTrue("Written file should appear in listing", names.contains(TEST_FILE_NAME));
        } finally {
            Files.deleteIfExists(file);
        }
    }

    @Test
    public void overwriteReplacesContent() throws IOException {
        var storage = requireStorage();
        var file = storage.resolve(TEST_FILE_NAME);

        Files.write(file, "first-and-longer".getBytes(java.nio.charset.StandardCharsets.UTF_8));
        Files.write(file, "second".getBytes(java.nio.charset.StandardCharsets.UTF_8));
        try {
            assertEquals("second", new String(Files.readAllBytes(file), java.nio.charset.StandardCharsets.UTF_8));
            long count = listChildren(storage).stream()
                .filter(p -> p.getFileName().toString().equals(TEST_FILE_NAME))
                .count();
            assertEquals("Overwrite should not leave a duplicate entry", 1, count);
        } finally {
            Files.deleteIfExists(file);
        }
    }

    @Test(expected = FileAlreadyExistsException.class)
    public void createNewFailsWhenFileExists() throws IOException {
        var storage = requireStorage();
        var file = storage.resolve(TEST_FILE_NAME);
        Files.write(file, new byte[]{1, 2, 3});
        try {
            Files.newByteChannel(file, java.util.Set.of(StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE)).close();
        } finally {
            Files.deleteIfExists(file);
        }
    }

    @Test
    public void deleteWrittenFileDisappearsFromListing() throws IOException {
        var storage = requireStorage();
        var file = storage.resolve(TEST_FILE_NAME);

        Files.write(file, new byte[]{4, 5, 6});
        Files.delete(file);

        assertFalse("Deleted file should not exist", Files.exists(file));
    }

    // --- move path ---

    @Test
    public void moveRenamesWithinSameDirectory() throws IOException {
        var storage = requireStorage();
        var src = storage.resolve(TEST_FILE_NAME);
        var dst = storage.resolve(TEST_FILE_NAME2);
        var payload = "rename me".getBytes(java.nio.charset.StandardCharsets.UTF_8);

        Files.write(src, payload);
        try {
            Files.move(src, dst);
            assertFalse("Source should no longer exist after move", Files.exists(src));
            assertTrue("Target should exist after move", Files.exists(dst));
            assertArrayEquals("Moved content should be preserved", payload, Files.readAllBytes(dst));
        } finally {
            Files.deleteIfExists(src);
            Files.deleteIfExists(dst);
        }
    }

    @Test
    public void moveRelocatesIntoSubdirectory() throws IOException {
        var storage = requireStorage();
        var dir = storage.resolve(TEST_DIR_NAME);
        var src = storage.resolve(TEST_FILE_NAME);
        var dst = dir.resolve(TEST_FILE_NAME);
        var payload = "relocate me".getBytes(java.nio.charset.StandardCharsets.UTF_8);

        Files.createDirectory(dir);
        Files.write(src, payload);
        try {
            Files.move(src, dst);
            assertFalse("Source should no longer exist after move", Files.exists(src));
            assertTrue("Target in subdirectory should exist", Files.exists(dst));
            assertArrayEquals("Relocated content should be preserved", payload, Files.readAllBytes(dst));

            var names = listChildren(dir).stream()
                .map(p -> p.getFileName().toString())
                .collect(Collectors.toList());
            assertTrue("Moved file should appear in the subdirectory listing", names.contains(TEST_FILE_NAME));
        } finally {
            Files.deleteIfExists(dst);
            Files.deleteIfExists(src);
            Files.deleteIfExists(dir);
        }
    }

    @Test(expected = FileAlreadyExistsException.class)
    public void moveFailsWhenTargetExistsWithoutReplace() throws IOException {
        var storage = requireStorage();
        var src = storage.resolve(TEST_FILE_NAME);
        var dst = storage.resolve(TEST_FILE_NAME2);
        Files.write(src, new byte[]{1});
        Files.write(dst, new byte[]{2});
        try {
            Files.move(src, dst);
        } finally {
            Files.deleteIfExists(src);
            Files.deleteIfExists(dst);
        }
    }

    @Test
    public void moveReplacesExistingTarget() throws IOException {
        var storage = requireStorage();
        var src = storage.resolve(TEST_FILE_NAME);
        var dst = storage.resolve(TEST_FILE_NAME2);
        Files.write(src, "winner".getBytes(java.nio.charset.StandardCharsets.UTF_8));
        Files.write(dst, "loser".getBytes(java.nio.charset.StandardCharsets.UTF_8));
        try {
            Files.move(src, dst, StandardCopyOption.REPLACE_EXISTING);
            assertFalse(Files.exists(src));
            assertEquals("winner", new String(Files.readAllBytes(dst), java.nio.charset.StandardCharsets.UTF_8));
        } finally {
            Files.deleteIfExists(src);
            Files.deleteIfExists(dst);
        }
    }

    @Test
    public void moveEmptyDirectorySucceeds() throws IOException {
        var storage = requireStorage();
        var srcDir = storage.resolve(TEST_DIR_NAME);
        var dstDir = storage.resolve(TEST_DIR_NAME2);

        Files.createDirectory(srcDir);
        try {
            Files.move(srcDir, dstDir);
            assertFalse("Source directory should be gone after move", Files.exists(srcDir));
            assertTrue("Target directory should exist after move", Files.isDirectory(dstDir));
        } finally {
            deleteTreeQuietly(srcDir);
            deleteTreeQuietly(dstDir);
        }
    }

    @Test
    public void moveNonEmptyDirectoryThrowsWhenNotNativelySupported() throws IOException {
        // A device without native MTP MoveObject cannot relocate a non-empty directory to a
        // different folder without moving its entries. Per the Files.move contract the provider's
        // emulation must fail with DirectoryNotEmptyException rather than recursively copy. Devices
        // that do implement MoveObject relocate the tree in one native operation, so the emulation
        // path under test is never reached there; probe the device and skip when that is the case.
        var storage = requireStorage();
        var srcDir = storage.resolve(TEST_DIR_NAME);
        var destParent = storage.resolve(TEST_DIR_NAME2);
        var moved = destParent.resolve(TEST_DIR_NAME);

        Files.createDirectory(srcDir);
        Files.write(srcDir.resolve("child.bin"), new byte[]{1, 2, 3});
        Files.createDirectory(destParent);
        try {
            DirectoryNotEmptyException refused = null;
            try {
                Files.move(srcDir, moved);
            } catch (DirectoryNotEmptyException e) {
                refused = e;
            }
            assumeTrue("device supports native directory move; emulation path not exercised",
                refused != null);

            // The emulation refused the move: the source must be untouched and the target absent.
            assertTrue("Source directory should still exist", Files.isDirectory(srcDir));
            assertTrue("Source child should still exist", Files.isRegularFile(srcDir.resolve("child.bin")));
            assertFalse("Target should not have been created", Files.exists(moved));
        } finally {
            deleteTreeQuietly(srcDir);
            deleteTreeQuietly(destParent);
        }
    }

    // --- copy ---

    @Test
    public void copyFileCreatesIndependentCopy() throws IOException {
        var storage = requireStorage();
        var src = storage.resolve(TEST_FILE_NAME);
        var dst = storage.resolve(TEST_FILE_NAME2);
        var payload = "copy me".getBytes(java.nio.charset.StandardCharsets.UTF_8);

        Files.write(src, payload);
        try {
            Files.copy(src, dst);
            assertTrue("Source should still exist after copy", Files.isRegularFile(src));
            assertTrue("Target should exist after copy", Files.isRegularFile(dst));
            assertArrayEquals("Copied content should match the source", payload, Files.readAllBytes(dst));
        } finally {
            Files.deleteIfExists(src);
            Files.deleteIfExists(dst);
        }
    }

    @Test(expected = FileAlreadyExistsException.class)
    public void copyFailsWhenTargetExistsWithoutReplace() throws IOException {
        var storage = requireStorage();
        var src = storage.resolve(TEST_FILE_NAME);
        var dst = storage.resolve(TEST_FILE_NAME2);
        Files.write(src, new byte[]{1});
        Files.write(dst, new byte[]{2});
        try {
            Files.copy(src, dst);
        } finally {
            Files.deleteIfExists(src);
            Files.deleteIfExists(dst);
        }
    }

    @Test
    public void copyReplacesExistingTarget() throws IOException {
        var storage = requireStorage();
        var src = storage.resolve(TEST_FILE_NAME);
        var dst = storage.resolve(TEST_FILE_NAME2);
        Files.write(src, "new".getBytes(java.nio.charset.StandardCharsets.UTF_8));
        Files.write(dst, "old-and-longer".getBytes(java.nio.charset.StandardCharsets.UTF_8));
        try {
            Files.copy(src, dst, StandardCopyOption.REPLACE_EXISTING);
            assertEquals("new", new String(Files.readAllBytes(dst), java.nio.charset.StandardCharsets.UTF_8));
            assertTrue("Source should remain after copy", Files.isRegularFile(src));
        } finally {
            Files.deleteIfExists(src);
            Files.deleteIfExists(dst);
        }
    }

    @Test
    public void copyDirectoryIsNonRecursive() throws IOException {
        var storage = requireStorage();
        var srcDir = storage.resolve(TEST_DIR_NAME);
        var dstDir = storage.resolve(TEST_DIR_NAME2);
        Files.createDirectory(srcDir);
        Files.write(srcDir.resolve("child.bin"), new byte[]{9});
        try {
            Files.copy(srcDir, dstDir);
            assertTrue("Target directory should be created", Files.isDirectory(dstDir));
            // Per the Files.copy contract, copying a directory creates the directory only.
            assertFalse("Directory entries should not be copied recursively",
                Files.exists(dstDir.resolve("child.bin")));
        } finally {
            deleteTreeQuietly(srcDir);
            deleteTreeQuietly(dstDir);
        }
    }

    // --- append & large-file streaming ---

    @Test
    public void appendExtendsExistingFile() throws IOException {
        var storage = requireStorage();
        var file = storage.resolve(TEST_FILE_NAME);
        Files.write(file, "first".getBytes(java.nio.charset.StandardCharsets.UTF_8));
        try {
            Files.write(file, "-second".getBytes(java.nio.charset.StandardCharsets.UTF_8),
                StandardOpenOption.APPEND);
            assertEquals("first-second",
                new String(Files.readAllBytes(file), java.nio.charset.StandardCharsets.UTF_8));
        } finally {
            Files.deleteIfExists(file);
        }
    }

    @Test
    public void largeFileRoundTripStreams() throws IOException {
        var storage = requireStorage();
        var file = storage.resolve(TEST_FILE_NAME);
        var payload = new byte[4 * 1024 * 1024]; // 4 MiB: exercises the streamed read/write path
        for (int i = 0; i < payload.length; i++) {
            payload[i] = (byte) (i * 31 + 7);
        }

        Files.write(file, payload);
        try {
            assertEquals("Reported size should match the written length", payload.length, Files.size(file));
            assertArrayEquals("Large round-tripped content should match", payload, Files.readAllBytes(file));
        } finally {
            Files.deleteIfExists(file);
        }
    }

    // --- isSameFile ---

    @Test
    public void isSameFileTrueForEquivalentPaths() throws IOException {
        var storage = requireStorage();
        var a = storage.resolve(TEST_FILE_NAME);
        var b = storage.resolve(TEST_FILE_NAME);
        Files.write(a, new byte[]{1});
        try {
            assertTrue("Two paths resolving to the same object should be the same file",
                Files.isSameFile(a, b));
            assertTrue("A path should be the same file as itself", Files.isSameFile(a, a));
        } finally {
            Files.deleteIfExists(a);
        }
    }

    @Test
    public void isSameFileFalseForDifferentPaths() throws IOException {
        var storage = requireStorage();
        var a = storage.resolve(TEST_FILE_NAME);
        var b = storage.resolve(TEST_FILE_NAME2);
        Files.write(a, new byte[]{1});
        Files.write(b, new byte[]{2});
        try {
            assertFalse("Distinct paths should not be the same file", Files.isSameFile(a, b));
        } finally {
            Files.deleteIfExists(a);
            Files.deleteIfExists(b);
        }
    }

    // --- isHidden ---

    @Test
    public void isHiddenAlwaysFalse() throws IOException {
        var storage = requireStorage();
        var file = storage.resolve(TEST_FILE_NAME);
        Files.write(file, new byte[]{7});
        try {
            assertFalse("MTP filesystem reports no hidden files", Files.isHidden(file));
            assertFalse("Storage root should not be hidden", Files.isHidden(storage));
        } finally {
            Files.deleteIfExists(file);
        }
    }

    // --- checkAccess ---

    @Test
    public void checkAccessSucceedsForReadAndWriteOnExistingFile() throws IOException {
        var storage = requireStorage();
        var file = storage.resolve(TEST_FILE_NAME);
        Files.write(file, new byte[]{1, 2, 3});
        try {
            // No exception means access is granted.
            provider.checkAccess(file);
            provider.checkAccess(file, AccessMode.READ);
            provider.checkAccess(file, AccessMode.WRITE);
        } finally {
            Files.deleteIfExists(file);
        }
    }

    @Test
    public void checkAccessExecuteThrowsAccessDenied() throws IOException {
        var storage = requireStorage();
        var file = storage.resolve(TEST_FILE_NAME);
        Files.write(file, new byte[]{1});
        try {
            assertThrows(AccessDeniedException.class,
                () -> provider.checkAccess(file, AccessMode.EXECUTE));
        } finally {
            Files.deleteIfExists(file);
        }
    }

    @Test(expected = NoSuchFileException.class)
    public void checkAccessThrowsForMissingFile() throws IOException {
        var storage = requireStorage();
        provider.checkAccess(storage.resolve(TEST_FILE_NAME));
    }

    // --- attribute views / string attributes ---

    @Test
    public void basicFileAttributeViewReadsAttributes() throws IOException {
        var storage = requireStorage();
        var file = storage.resolve(TEST_FILE_NAME);
        var payload = new byte[]{1, 2, 3, 4, 5};
        Files.write(file, payload);
        try {
            var view = Files.getFileAttributeView(file, BasicFileAttributeView.class);
            assertNotNull("BasicFileAttributeView should be available", view);
            var attrs = view.readAttributes();
            assertTrue("View should report the file as a regular file", attrs.isRegularFile());
            assertEquals("View should report the written size", payload.length, attrs.size());
        } finally {
            Files.deleteIfExists(file);
        }
    }

    @Test
    public void setTimesViaViewIsUnsupported() throws IOException {
        var storage = requireStorage();
        var file = storage.resolve(TEST_FILE_NAME);
        Files.write(file, new byte[]{1});
        try {
            var view = Files.getFileAttributeView(file, BasicFileAttributeView.class);
            assertThrows(UnsupportedOperationException.class,
                () -> view.setTimes(FileTime.fromMillis(0), null, null));
        } finally {
            Files.deleteIfExists(file);
        }
    }

    @Test
    public void readStringAttributesReturnsRequestedKeys() throws IOException {
        var storage = requireStorage();
        var file = storage.resolve(TEST_FILE_NAME);
        var payload = new byte[]{1, 2, 3, 4};
        Files.write(file, payload);
        try {
            var attrs = Files.readAttributes(file, "basic:size,isRegularFile,isDirectory");
            assertEquals("Only the requested keys should be returned", 3, attrs.size());
            assertEquals((long) payload.length, attrs.get("size"));
            assertEquals(Boolean.TRUE, attrs.get("isRegularFile"));
            assertEquals(Boolean.FALSE, attrs.get("isDirectory"));
        } finally {
            Files.deleteIfExists(file);
        }
    }

    @Test
    public void readStringAttributesWildcardReturnsAllBasicKeys() throws IOException {
        var storage = requireStorage();
        var file = storage.resolve(TEST_FILE_NAME);
        Files.write(file, new byte[]{1});
        try {
            var attrs = Files.readAttributes(file, "*");
            assertTrue("Wildcard should include size", attrs.containsKey("size"));
            assertTrue("Wildcard should include isDirectory", attrs.containsKey("isDirectory"));
            assertTrue("Wildcard should include fileKey", attrs.containsKey("fileKey"));
            assertTrue("Wildcard should include lastModifiedTime", attrs.containsKey("lastModifiedTime"));
        } finally {
            Files.deleteIfExists(file);
        }
    }

    @Test
    public void readUnknownStringAttributeThrows() throws IOException {
        var storage = requireStorage();
        var file = storage.resolve(TEST_FILE_NAME);
        Files.write(file, new byte[]{1});
        try {
            assertThrows(IllegalArgumentException.class,
                () -> Files.readAttributes(file, "basic:notAnAttribute"));
        } finally {
            Files.deleteIfExists(file);
        }
    }

    @Test
    public void setAttributeIsUnsupported() throws IOException {
        var storage = requireStorage();
        var file = storage.resolve(TEST_FILE_NAME);
        Files.write(file, new byte[]{1});
        try {
            assertThrows(UnsupportedOperationException.class,
                () -> Files.setAttribute(file, "basic:lastModifiedTime", FileTime.fromMillis(0)));
        } finally {
            Files.deleteIfExists(file);
        }
    }

    // --- track metadata ("mtp" attribute view) ---

    @Test
    public void trackMetadataViewHasExpectedShape() throws IOException {
        var storage = requireStorage();
        var file = requireRegularFile(storage);

        var attrs = Files.readAttributes(file, "mtp:*");
        assertEquals(Set.of("title", "artist", "album", "genre", "trackNumber", "durationMillis"),
            attrs.keySet());
    }

    @Test
    public void trackMetadataReadsForAudioFileWithoutTransferringContent() throws IOException {
        var storage = requireStorage();
        var audio = requireAudioFile(storage);

        long start = System.nanoTime();
        var attrs = Files.readAttributes(audio, "mtp:*");
        long elapsedMillis = (System.nanoTime() - start) / 1_000_000;

        // Diagnostic for the spike: how long a metadata-only read takes vs pulling the file.
        System.out.println("mtp:* for " + audio + " took " + elapsedMillis + "ms: " + attrs);
        assertEquals(Set.of("title", "artist", "album", "genre", "trackNumber", "durationMillis"),
            attrs.keySet());
        // A metadata read must be far cheaper than transferring the object; even the slowest
        // supported path (per-property GetObjectPropValue) stays well under this bound.
        assertTrue("metadata-only read took " + elapsedMillis + "ms", elapsedMillis < 5_000);
    }

    @Test
    public void partialReadPullsAudioHeaderWithoutTransferringWholeObject() throws IOException {
        var storage = requireStorage();
        var audio = requireAudioFile(storage);

        var bridge = MTPDeviceBridge.getInstance();
        var deviceId = fs.getDeviceIdentifier();
        var absPath = audio.toAbsolutePath().toString();
        long fullSize = Files.size(audio);

        long start = System.nanoTime();
        // 64 KB comfortably covers a FLAC STREAMINFO + VORBIS_COMMENT block for tag reading.
        byte[] head = bridge.readPartial(deviceId, absPath, 0, 64 * 1024);
        long elapsedMillis = (System.nanoTime() - start) / 1_000_000;

        System.out.printf("readPartial(64KB) of %s (%d bytes total) returned %d bytes in %dms%n",
            audio, fullSize, head.length, elapsedMillis);

        assertTrue("expected some header bytes", head.length > 0);
        assertTrue("ranged read must not transfer the whole object", head.length <= 64 * 1024);
        assertTrue("a ranged header read of a few KB should be far cheaper than a whole-object transfer",
            elapsedMillis < 5_000);

        // Proves we pulled real file bytes (the container magic), not device-indexed metadata.
        if (audio.getFileName().toString().toLowerCase().endsWith(".flac")) {
            assertTrue("FLAC header should be at least the 4-byte magic", head.length >= 4);
            assertEquals("expected FLAC 'fLaC' stream marker",
                "fLaC", new String(head, 0, 4, java.nio.charset.StandardCharsets.US_ASCII));
        }
    }

    @Test
    public void flacTagsReadFromHeaderRecoverRealTitle() throws Exception {
        var storage = requireStorage();
        var flac = requireFlac(storage);

        var bridge = MTPDeviceBridge.getInstance();
        var deviceId = fs.getDeviceIdentifier();
        var absPath = flac.toAbsolutePath().toString();

        // A ranged-read view of the device file via *pure java.nio* — Files.newByteChannel with
        // position()/read(), no melt-jfs types. This is exactly the seam a decoupled consumer uses;
        // the lazy channel fetches only the bytes read, so seeking past the album art costs nothing.
        RangedByteSource source = (off, n) -> {
            try (var ch = Files.newByteChannel(flac, StandardOpenOption.READ)) {
                ch.position(off);
                var buf = java.nio.ByteBuffer.allocate(n);
                while (buf.hasRemaining() && ch.read(buf) >= 0) { /* fill up to n or EOF */ }
                return java.util.Arrays.copyOf(buf.array(), buf.position());
            }
        };

        var blocks = FlacMetadataReader.describeBlocks(source);
        System.out.println("FLAC metadata blocks for " + flac + ":");
        long metadataSpan = 4;
        for (var b : blocks) {
            System.out.printf("  %-16s offset=%d length=%d last=%b%n",
                b.typeName(), b.offset(), b.length(), b.last());
            metadataSpan = b.offset() + 4 + b.length();
        }

        long start = System.nanoTime();
        byte[] minimal = FlacMetadataReader.minimalMetadataStream(source);
        long elapsedMillis = (System.nanoTime() - start) / 1_000_000;
        assertNotNull("expected a FLAC stream", minimal);

        // The whole point: what the device's MTP index reports (often the filename) vs. the embedded
        // tag we recover by parsing the header we pulled over ranged reads.
        var deviceMeta = bridge.getTrackMetadata(deviceId, absPath);
        var tag = readFlacTag(minimal);
        String embeddedTitle = tag.getFirst(FieldKey.TITLE);

        System.out.printf(
            "stitched %d bytes (file is %d bytes, metadata spans ~%d) in %dms | device-title=%s | embedded-title=%s%n",
            minimal.length, Files.size(flac), metadataSpan, elapsedMillis,
            deviceMeta == null ? null : deviceMeta.title(), embeddedTitle);

        assertTrue("stitched stream must be far smaller than the whole file",
            minimal.length < Files.size(flac));
        assertNotNull("embedded FLAC tag should expose a title", embeddedTitle);
        assertFalse("recovered title should not be blank", embeddedTitle.isBlank());
    }

    @Test
    public void audioViewRecoversEmbeddedTagsFromFlac() throws IOException {
        var storage = requireStorage();
        var flac = requireFlac(storage);

        // The pure-NIO seam: read embedded tags straight off the file via the "audio" attribute view.
        var audio = Files.readAttributes(flac, "audio:title,artist,album,durationMillis");
        // Contrast with the device's own index, which typically reports the filename as the title.
        var mtp = Files.readAttributes(flac, "mtp:title");

        System.out.printf("audio-view title=%s (artist=%s, album=%s, %sms) vs mtp title=%s%n",
            audio.get("title"), audio.get("artist"), audio.get("album"),
            audio.get("durationMillis"), mtp.get("title"));

        assertNotNull("audio view should recover an embedded title", audio.get("title"));
        assertFalse("recovered title should not be blank", ((String) audio.get("title")).isBlank());
    }

    @Test
    public void trackMetadataIsNullForDirectories() throws IOException {
        var storage = requireStorage();
        var bridge = MTPDeviceBridge.getInstance();
        var deviceId = fs.getDeviceIdentifier();
        assertNull(bridge.getTrackMetadata(deviceId, storage.toAbsolutePath().toString()));
    }

    // The "audio" attribute view parses embedded tags from the file's own bytes (ranged reads), so it
    // does not depend on the device's media index — every format is validated the same way: upload the
    // known-tagged fixture, then read audio:* straight back off the device.

    @Test
    public void audioViewReadsUploadedFlacTags() throws IOException {
        assertAudioViewOfUploadedFixture("fixture.flac", 2);
    }

    @Test
    public void audioViewReadsUploadedMp3Tags() throws IOException {
        assertAudioViewOfUploadedFixture("fixture.mp3", 2);
    }

    @Test
    public void audioViewReadsUploadedM4aTags() throws IOException {
        assertAudioViewOfUploadedFixture("fixture.m4a", 2);
    }

    @Test
    public void audioViewReadsUploadedOggTags() throws IOException {
        assertAudioViewOfUploadedFixture("fixture.ogg", 2);
    }

    @Test
    public void audioViewReadsUploadedOpusTags() throws IOException {
        assertAudioViewOfUploadedFixture("fixture.opus", 2);
    }

    @Test
    public void audioViewReadsUploadedWavTags() throws IOException {
        // RIFF INFO has no disc-number field, so a WAV recovers discNumber 0.
        assertAudioViewOfUploadedFixture("fixture.wav", 0);
    }

    /**
     * Uploads the checked-in {@code fixtureName} to the device, reads its embedded tags back through the
     * {@code audio} attribute view, and asserts the known fixture tags. Unlike the {@code mtp} view (the
     * device's index), this parses the file's own bytes over ranged reads, so no indexing wait is needed.
     */
    private void assertAudioViewOfUploadedFixture(String fixtureName, int expectedDisc) throws IOException {
        byte[] fixture;
        try (var in = getClass().getResourceAsStream("/fixtures/" + fixtureName)) {
            // Checked into integrationTest resources, so a missing one is a build packaging bug.
            assertNotNull("fixture /fixtures/" + fixtureName + " not on classpath", in);
            fixture = in.readAllBytes();
        }

        var storage = requireStorage();
        var extension = fixtureName.substring(fixtureName.lastIndexOf('.'));
        var target = storage.resolve(AUDIO_FIXTURE_BASE + extension);

        Files.write(target, fixture);
        try {
            var attrs = Files.readAttributes(target, "audio:*");
            System.out.printf("audio:* for uploaded %s -> %s%n", fixtureName, attrs);

            assertEquals(fixtureName + " title", FIXTURE_TITLE, attrs.get("title"));
            assertEquals(fixtureName + " artist", FIXTURE_ARTIST, attrs.get("artist"));
            assertEquals(fixtureName + " album", FIXTURE_ALBUM, attrs.get("album"));
            assertEquals(fixtureName + " genre", FIXTURE_GENRE, attrs.get("genre"));
            assertEquals(fixtureName + " trackNumber", FIXTURE_TRACK, attrs.get("trackNumber"));
            assertEquals(fixtureName + " discNumber", expectedDisc, attrs.get("discNumber"));

            long durationMillis = (Long) attrs.get("durationMillis");
            assertEquals(fixtureName + " duration (s)", FIXTURE_DURATION_SECONDS,
                Math.round(durationMillis / 1000.0));
        } finally {
            Files.deleteIfExists(target);
        }
    }

    @Test
    public void uploadedId3v23Mp3TagsAreReadBackViaAudioView() throws IOException {
        var storage = requireStorage();

        // A ~1s silent MP3 carrying these exact ID3v2.3 tags, checked in under integrationTest resources.
        byte[] fixture;
        try (var in = getClass().getResourceAsStream(META_FIXTURE)) {
            // The fixture is checked into integrationTest resources, so a missing one is a build
            // packaging bug, not an environmental condition — fail rather than skip.
            assertNotNull("tagged audio fixture " + META_FIXTURE + " not on classpath", in);
            fixture = in.readAllBytes();
        }

        var target = storage.resolve(META_FILE_NAME);
        Files.write(target, fixture);
        try {
            // Read the embedded tags back through the "audio" view: it parses the file's own bytes over
            // ranged reads, so it recovers the real ID3 tags immediately. (The device's "mtp" index is
            // not asserted here — many devices, e.g. this Pixel, report the filename as the title and
            // expose no other fields, which is exactly why the "audio" view exists.)
            var attrs = Files.readAttributes(target, "audio:*");

            assertEquals("melt-jfs Test Title",  attrs.get("title"));
            assertEquals("melt-jfs Test Artist", attrs.get("artist"));
            assertEquals("melt-jfs Test Album",  attrs.get("album"));
            assertEquals("Jazz",                 attrs.get("genre"));
            assertEquals(7,                      attrs.get("trackNumber"));
            // The fixture is ~1045ms of audio; duration is derived from the MP3 frames, in milliseconds.
            // A band (not an exact match) allows for rounding/derivation differences while still proving
            // the value is milliseconds — not seconds (~1) or 100ns units (~10.4M).
            long durationMillis = (Long) attrs.get("durationMillis");
            assertTrue("duration should be ~1s in millis, was " + durationMillis,
                durationMillis > 500 && durationMillis < 2_000);
        } finally {
            Files.deleteIfExists(target);
        }
    }

    // --- helpers ---

    private static final List<String> AUDIO_EXTENSIONS =
        List.of(".mp3", ".flac", ".ogg", ".m4a", ".wma", ".wav", ".opus", ".aac");

    // The read-path tests want real on-device content to exercise. Rather than skip on a device (or a
    // blank SD card) that happens to hold no suitable file, these helpers stage one from the checked-in
    // fixtures so the test still runs. Anything staged uses the test-artifact names that
    // cleanUpTestArtifacts() deletes in both setUp and tearDown, so nothing is left on the device.

    /** An existing regular file under {@code storage}, or a freshly staged one when it has none. */
    private Path requireRegularFile(Path storage) throws IOException {
        var found = findFirstFile(storage, 2);
        if (found != null) return found;
        var staged = storage.resolve(TEST_FILE_NAME);
        Files.write(staged, "melt-jfs staged content".getBytes(java.nio.charset.StandardCharsets.UTF_8));
        return staged;
    }

    /** An existing audio file under {@code storage}, or a staged FLAC fixture when it has none. */
    private Path requireAudioFile(Path storage) throws IOException {
        var found = findFirstAudioFile(storage, 4);
        return found != null ? found : stageFlacFixture(storage);
    }

    /** An existing .flac under {@code storage}, or a staged FLAC fixture when it has none. */
    private Path requireFlac(Path storage) throws IOException {
        var found = findFirstFlac(storage, 4);
        return found != null ? found : stageFlacFixture(storage);
    }

    /** Uploads the checked-in FLAC fixture to {@code storage} and returns its path. */
    private Path stageFlacFixture(Path storage) throws IOException {
        byte[] fixture;
        try (var in = getClass().getResourceAsStream("/fixtures/fixture.flac")) {
            // Checked into integrationTest resources, so a missing one is a build packaging bug.
            assertNotNull("fixture /fixtures/fixture.flac not on classpath", in);
            fixture = in.readAllBytes();
        }
        var target = storage.resolve(AUDIO_FIXTURE_BASE + ".flac");
        Files.write(target, fixture);
        return target;
    }

    private Path findFirstAudioFile(Path dir, int depthRemaining) throws IOException {
        try (var stream = Files.newDirectoryStream(dir)) {
            for (var child : stream) {
                var name = child.getFileName().toString().toLowerCase();
                if (Files.isRegularFile(child) && AUDIO_EXTENSIONS.stream().anyMatch(name::endsWith)) {
                    return child;
                }
                if (Files.isDirectory(child) && depthRemaining > 0) {
                    var found = findFirstAudioFile(child, depthRemaining - 1);
                    if (found != null) return found;
                }
            }
        }
        return null;
    }

    private Path findFirstFlac(Path dir, int depthRemaining) throws IOException {
        try (var stream = Files.newDirectoryStream(dir)) {
            for (var child : stream) {
                if (Files.isRegularFile(child)
                        && child.getFileName().toString().toLowerCase().endsWith(".flac")) {
                    return child;
                }
                if (Files.isDirectory(child) && depthRemaining > 0) {
                    var found = findFirstFlac(child, depthRemaining - 1);
                    if (found != null) return found;
                }
            }
        }
        return null;
    }

    private static org.jaudiotagger.tag.Tag readFlacTag(byte[] flac) throws Exception {
        Path tmp = Files.createTempFile("melt-jfs-flac", ".flac");
        try {
            Files.write(tmp, flac);
            return AudioFileIO.read(tmp.toFile()).getTag();
        } finally {
            Files.deleteIfExists(tmp);
        }
    }

    private Path requireStorage() {
        assumeTrue("No storage available on device", storage != null);
        return storage;
    }

    private List<Path> listChildren(Path dir) throws IOException {
        var result = new ArrayList<Path>();
        try (var stream = Files.newDirectoryStream(dir)) {
            stream.forEach(result::add);
        }
        return result;
    }

    private Path findFirstFile(Path dir, int depthRemaining) throws IOException {
        try (var stream = Files.newDirectoryStream(dir)) {
            for (var child : stream) {
                if (Files.isRegularFile(child)) return child;
                if (Files.isDirectory(child) && depthRemaining > 0) {
                    var found = findFirstFile(child, depthRemaining - 1);
                    if (found != null) return found;
                }
            }
        }
        return null;
    }

    private static boolean isBackendAvailable() {
        try {
            // Loads the platform's native backend: libmtp on Linux/macOS, WPD (ole32) on Windows.
            MtpBackend.defaultBackend();
            return true;
        } catch (Throwable t) {
            return false;
        }
    }
}
